services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: unless-stopped
    
    ports:
      - "127.0.0.1:6190:6190"
    
    volumes:
      - .:/app
    
    user: "1000:1000"
    
    environment:
      - PYTHONPATH=/app