# Внимание: io-раздел отведён чисто под тестирование.
# API обращается по любым аргументам.
io:
  input_folder: "data/input/" # Папка для входных фото
  image_name: "image.jpg"
  output_folder: "data/output/" # Папка для результатов и артефактов

models:
  path: "models/"

# Конфигурация модели сегментации.
seg-model:
  path: "models/best_seg.pt"
  trim_top_pct: 0.3
  trim_bottom_pct: 0.15
  final_size: 244
  debug: False

# Конфигурация модели идентификации.
id-model:
  path: "models/best_model.pth"
  embedding_dim: 512  # Неактивно
  droupout_rate: 0.4  # Неактивно

# Конфигурация бд и faiss.
db:
  db_path: "database/cards.db"
  faiss_index_path: "data/embeddings/database_embeddings.pkl"
  cropped_folder: "data/cropped/"

view:
  size_answer: 20  # Размер рейтинга