models:
  path: "models/"

# Конфигурация модели сегментации.
seg-model:
  path: "models/best_seg.pt"
  trim_top_pct: 0.3
  trim_bottom_pct: 0.15
  final_size: 244
  debug: False  # Неактивно, меняется в аргументах

# Конфигурация модели идентификации.
id-model:
  path: "models/best_model.pth"
  embedding_dim: 512  # Неактивно
  droupout_rate: 0.4  # Неактивно

# Конфигурация бд и faiss.
db:
  db_path: "database/cards.db"
  faiss_index_path: "data/embeddings/database_embeddings.pkl"
  cropped_folder: "data/cropped/"
  full_folder: "data/full/"
  "expiry_hours": 0.00001  # Через сколько просрочиваются записи в uploads

view:
  size_answer: 5  # Размер рейтинга (теперь неактивно, меняется в аргументах во входе)